services:
  - type: web
    name: drithi-agro-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: DB_HOST
        value: dpg-d9s1if2jnfac738kstt0-a.singapore-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: drithi_agro_uv0v
      - key: DB_USER
        value: drithi_agro_uv0v_user
      - key: DB_PASS
        value: oYPKcuzlzSF5mvCIFQrr4I9quYJC0Z5p
      - key: JWT_SECRET
        value: dr!th!Agr0#2025$S3cur3K3y@xAmPP^JWT&S3cr3t
      - key: JWT_EXPIRY
        value: "86400"
      - key: APP_URL
        value: https://dhrithi-agro-backend-2.onrender.com
